### ISSUE TITLE
Some pages are not reachable - blanc pages

### ISSUE THREAD

**Issue by mtrabelsi** [iotaledger/documentation-platform#204]
1- go to : https://docs.iota.org/search?q=iri
2. click the first link (https://docs.iota.org/docs/compass/0.1/how-to-guides/create-an-iota-network?q=iri&highlights=tree;time;sure;sign;side;servic;script;port;more;minut;merkl;linux;line;iri;guid;grpc;free;first;finish;file;field;error;dure;core;basic;avoid;again;addit;activ)

you will get a blanc page!

**Comment by obany** [comment]
The search highlight was corrupting the named anchors and so the toc scrolling couldn't find the element resulting in a null element.

Fixed in https://github.com/iotaledger/documentation-platform/commit/fee301ca64a9a84295025d8261f7216b0a8f22aa
