### ISSUE TITLE
Improve Search quality

### ISSUE THREAD

**Issue by obany** [iotaledger/documentation-platform#206]
Investigate other search libraries or APIs and produce some test cases with results.

- [ ] Algolia https://www.algolia.com/
- [ ] Elastic Search https://www.elastic.co/
- [ ] Amazon Cloud Search https://aws.amazon.com/cloudsearch/
- [ ] Solr http://lucene.apache.org/solr/
- [ ] Lunr https://lunrjs.com/ (Current, maybe better search parameters)
... Others

Also can we get stats on searches so we can populate the Popular Topics programatically.

**Comment by Citrullin** [comment]
Thanks for this issue. An important topic, I think :) Since we are an open source foundation, we also should prefer open source solutions and in the best case, contribute to other open source projects, if we find some issues. The industry standard is Solr or Elasticsearch. Both is based on Lucene.

**Comment by obany** [comment]
Fixed with this PR https://github.com/iotaledger/documentation-platform/pull/259
