### ISSUE TITLE
Grammar & Spell-checking for Markdown

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/documentation-platform#208]
Most IDEs only contain spell-checking. Therefore, it would make sense to add some kind of additional spell- & grammar-checking for the documentation. E.g. [LanguageTool has an API for this.](https://languagetoolplus.com/http-api/#/default)

We could enable to spell- & grammar-checking for every Pull-Request. Probably there is no ready-to-use solution for this.

**Comment by JakeSCahill** [comment]
Language tool is great. I've used it before with the term checker : https://www.simplified-english.co.uk/index.html

Mike Unwalla allows me to use it for free for testing, but if we decide to use it, I could ask him if we could have a license

**Comment by Citrullin** [comment]
@JakeSCahill Sounds great. So, we could use the REST API for test purposes. Nice! I found [this nodejs](https://github.com/schreiben/node-languagetool) module. Maybe it is worth to take a look into it.

**Comment by JakeSCahill** [comment]
Language Tool seems to have some limitations: http://wiki.languagetool.org/public-http-api

I don't think this will work. I'm looking into some other options such as the [`rousseau` module](https://github.com/GitbookIO/rousseau).

**Comment by JakeSCahill** [comment]
https://github.com/iotaledger/documentation/pull/194

I think grammar is a difficult one. Sometimes, it's subjective and really should be something we add to a style guide. The spell checker is a nice addition for now.

I'd recommend using this to check grammar before pushing to the repo: http://www.hemingwayapp.com/
