### ISSUE TITLE
SEO: Redirect for changed URLs 

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/documentation-platform#209]
It might happen at some point that we need to change the URLs. e.g. Restructuring. 
We will lose all links if we do not have any redirect mechanism. Therefore, we will lose ranking in search engines. Instead, we should introduce some kind revision system, so that the URLs get redirected after change.

**Comment by obany** [comment]
This is partially address by the new feature which adds root level redirects for the project names https://github.com/iotaledger/documentation-platform/pull/219, but a more configurable option may also be necessary.

If content is reorganized within a section the ability to add an alias-index.md to sit alongside the doc-index.md would allow for automatic redirect creation.
