### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#21]

**Comment by sobolev-alexey** [comment]
The implementation will be based on the `Lunr` demo project from this repo: https://github.com/olivernn/moonwalkers

**Comment by jakubcech** [comment]
Lunr will be perfect for our needs, we can decide later if it's not sufficient, but with the highlighting part that you put in I think it's great. As long as it doesn't impose any limits on the style of the website, which iiuc it doesn't. 

Thanks!
