### ISSUE TITLE
Multilingual docs

### ISSUE THREAD

**Issue by navin1976** [iotaledger/documentation-platform#211]
The site should allow for community-sourced translations of the docs.
Contributions could be via Crowdin (as used for Trinity)

As suggested by @JakeSCahill:
```
We can start by writing translation guidelines, including a termbase (that tells translators how to translate our terms to be consistent with the ones we use in Trinity), what to do with code samples (whether to translate comments or even strings).
```

**Comment by rajivshah3** [comment]
That's a great idea. I can help set that up if needed. 

> including a termbase (that tells translators how to translate our terms to be consistent with the ones we use in Trinity)

Crowdin has a [Glossary](https://support.crowdin.com/glossary/) feature that allows this. We can also use the [Translation Memory](https://support.crowdin.com/translation-memory/) feature to allow translators to see how strings were translated in Trinity.

**Comment by JakeSCahill** [comment]
Awesome, thanks @rajivshah3 . That would be great. I've never used Crowin, but if I write a guideline doc, could we add that to the project?

**Comment by JakeSCahill** [comment]
I've created some guidelines. What are the next steps? Can you create a Crowdin project that can host the glossaries and translation guidelines?

**Comment by JakeSCahill** [comment]
An issue exists on the doc site for this too. We have discussed some early thoughts about how this could be done: https://github.com/iotaledger/documentation/issues/284
