### ISSUE TITLE
Support for different message boxes

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#212]
### Description
Suggested by Luca on Discord that we could have different information boxes to convey that something is a warning, an information, a danger, a success. Or something similar. Confluence has a similar boxes as well, for example. 

https://media.discordapp.net/attachments/502455245620641792/544823097426051073/unknown.png

Martyn suggested:
Martyn Janes [IF]Today at 11:17 AM
we could stick to their same syntax

:::success Yes 🎉 :::

:::info This is a message 📣 :::

:::warning Watch out ⚡️ :::

:::danger Oh No! 🔥 :::

**Comment by obany** [comment]
We should ask @digital-zen nicely to create our own IF styled versions :)
