### ISSUE TITLE
Support for IE11

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#213]
### Description
The site currently doesn't work on IE11. It was a design decision to focus on Edge instead of IE11 from MS browsers, as Edge is recommended anyway. There are still (corporate) customers with policies forcing them to use IE11 though. We should look at how costly it would be to make the site work on IE11, and if too costly, just display a disclaimer that you should upgrade.

**Comment by obany** [comment]
We have had nobody ask about this in over a year that the site has been up, closing
