### ISSUE TITLE
Design the layout of individual elements

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#24]

**Comment by NelsonPython** [comment]
/* IOTA Docs Style Sheet v0.1	*/
/* Nelson@iota.org		*/

html, body {background-color: #fff;color: #000;}

body {
  position: relative;
  min-height: 100%;
  margin: 0;
  padding-bottom: 6rem;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
  text-rendering: optimizeLegibility;
}


div {font-weight: 400;font-size: 14px;line-height: 24px;margin-bottom: 20px;border: 0;margin: 50px 30px;font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto','Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans','Helvetica Neue', sans-serif;}
span {font-weight: 600;}
p {font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto','Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans','Helvetica Neue', sans-serif; font-weight: 400;font-size: 14px;line-height: 24px;}


/* TEXT */
html {font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif}
h1,h2,h3,h4,h5 {font-weight:400;line-height:1}
h1 a,h2 a,h3 a,h4 a,h5 a,h6 a {font-weight:inherit;}
h1 {font-size:26px}
h2 {font-size:18px;font-weight: bold}
h3 {font-size:14px;font-weight: bold}
h4 {font-size:14px;font-weight: bold;color: #ADD8E6}
h5 {font-size:13px;font-weight: bold;color: #FFA500}

h6 {color: #007070;font-size: 0.9em;FONT_FAMILY_MONO =  'Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif'}


/* LINKS */
a {text-decoration: none;color: #067df7;font-size: inherit}
a:hover {text-decoration: underline}
a.dark {color: #fff;border-bottom: 1px solid #fff}
a.dark:hover {text-decoration: underline}


/* LISTS */
ul {padding: 0;list-style: none}
li {font-size: 14px;line-height: 24px;margin-bottom: 10px}
li:before{padding-left: 18px;content: "-";padding-right: 8px}


/* BLOCKQUOTE */
blockquote {padding: 10px 20px;border-left: 5px solid #000;margin: 20px 0;color: #888;}
blockquote.dark {border-left-color: #fff;}

**Comment by l3wi** [comment]
@NelsonPython My understanding is @digital-zen will be providing layout and scheme of the elements based on his developer feedback
