### ISSUE TITLE
HUB

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#36]
Test the RPC Hub documentation

- [x] A list of what is missing/can be improved from initial testing.

**Comment by sobolev-alexey** [comment]
Repository: https://github.com/iotaledger/rpchub

**Comment by sobolev-alexey** [comment]
General:
Very high level of technical understanding, awareness of IOTA ecosystem and tools and pre-installed software is assumed.
For people looking into this project with no experience in IOTA there is a very little chance to complete all assumed steps and start using the HUB.

Main *README.md* file
1. If there exist a blog article, no link to it is provided.

2. https://github.com/iotaledger/rpchub#configuration
`If running on mainnet, set -minWeightMagnitude to at least 14` Not explained what `minWeightMagnitude` is and what is the possible value range.
`You MUST pass a -salt parameter.` Why? And what this `salt` should consist of? What are requirements for it's complexity and length?
`Run your own IRI node and specify endpoint via -apiAddress` Not explained how to run an own IRI node. If explained somewhere else, no link to the respective documentation page.

*Getting Started* page
1. Documentation is distributed across different folders, not all files have cross-references to files in other folder.

2. List of all required tools is missing.
Possible tools to list: Docker, Bazel, MariaDB

3. https://github.com/iotaledger/rpchub/blob/master/docs/getting_started.md#building-the-hub
`bazel build -c opt //hub:hub` 
What is Bazel, where to get it, how to install and configure?

4. https://github.com/iotaledger/rpchub/blob/master/docs/getting_started.md#setup-the-database-this-example-is-using-mariadb
`Install MariaDB (e.g. via Docker)` 
How to install and configure? 

5. https://github.com/iotaledger/rpchub/blob/master/docs/getting_started.md#run-via-docker
```Run via Docker
You can build a docker image for RPCHub via bazel build -c opt //docker:hub
```
What are the next steps to run and use the HUB via Docker?


*Test Plan* page
https://github.com/iotaledger/rpchub/blob/master/docs/pull_request_template.md
the page is empty.
 
*Securing Hub/Signing_Server * page
https://github.com/iotaledger/rpchub/blob/master/docs/secure_server.md
`see the provided Python example for further guidance`
Provided where?

*docs/python* folder
Not a single line of comment in all 3 files.
Used hard-coded values
