### ISSUE TITLE
Trinity

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#37]
Test the Trinity documentation

- [ ] A list of what is missing/can be improved from initial testing.

**Comment by mtrabelsi** [comment]
- the screenshots in the [old docs](https://docs.iota.works/trinity/what-is-trinity) are small 

- In the [old docs](https://docs.iota.works/trinity/what-is-trinity) there are sometimes mismatches between the subtitle and its content, for example the subtile "What is Trinity?" is not explaining What is Trinity, but rather act as a generic intro for the whole doc..

- The subsections (especially the installation guide ) doesn't feel linked, but rather it feels like disconnected from each other. ( when you read the next page its hard to get what is the previous one neither the next)

- This [subtitle](https://docs.iota.works/trinity/interact/wallet-actions) talking about foreground action when the user is doing an outgoing action ( like sending a transaction ) but not mentioning the case for incoming transactions, does it work, do you get notifications when you get funds ? or should you open the app and out it in the foreground?

- While it can really obvious for a lot of us, in this [section](https://docs.iota.works/trinity/interact/sending-funds) we should explain more the difference between : i, Mi, Gi.. To avoid any unhappy and confused readers.
