### ISSUE TITLE
Client lib - Python

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#41]

**Comment by jakubcech** [comment]
By Nelson:

o we want to harmonize the look and feel of iotasupport.com with dev.iota.org?

Fix broken links to dev.iota.org/sandbox or revise text - what is status of Sandbox?

What happens if I submit a message longer than 2187?

Do we want to update examples with Tyler's code for getNodeInfo, generateAddress, sendTranfer?

Add more information about how each security level is used because without the proper security level, API examples can throw errors

Integrate the "utils" feature in the extended API so it is easier to decipher the SMF

Examples for each API call would be helpful 

Test all the code snippets

Nice to have - a method for regression testing the code snippets to ensure they work after changes.  Maybe we could look into RobotFramework test automation?

What happens in DevNet when a random seed is generated and not used?

What happens to transactions with errors?

**Comment by NelsonPython** [comment]
We must add a note for devs to make sure that six is upgraded; otherwise, may get error "cannot import name 'python_2_unicode_compatible' from types.py
