### ISSUE TITLE
Test the implementations on providing suggestions in the documentation

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#47]
Test different frameworks for implementing the ability to provide suggest changes in the documentation. This would mean a user is able to edit the actual page. 

1. User opens a page she wants to suggest changes for.
2. User clicks a button for suggesting changes.
3. A window where user can make changes to the page opens.
4. User suggests the changes.
5. We are able to see and review the changes. 
6. We are able to merge the changes in the repo.

**Comment by sobolev-alexey** [comment]
Implemented 1-5. 
No styling, no loading indicators, just pure functionality.

6. The right approach to be discussed. 
I believe that automated PRs without review will create a lot of noise. 
Manual review and update the doc doesn't require any additional coding.
