### ISSUE TITLE
Set up analytics on the documentation website

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/documentation-platform#51]
### Description

- Page
     - Page view
     - Page load time
     - Time on page
     - Session duration
- Code examples (per language, per page)
      - Code example run

We should have a hotjar integration at some point

**Comment by jakubcech** [comment]
@l3wi can we reuse the existing analytics solution that is set up on the current site? Aka migrate over and keep the data so we have a comparison and historical data?

**Comment by obany** [comment]
Google analytics is wired in, it just needs `googleAnalyticsId` completing in config.json during deployment
